
name: Check Editor Config
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@v1.1.0
